### ISSUE TITLE
Support JPQL

### ISSUE THREAD

**Issue by ukupat** [zeroturnaround/sql-formatter#10]
https://www.tutorialspoint.com/jpa/jpa_jpql.htm

**Comment by seguri** [comment]
can we reopen this? I'd like to see sql-formatter support queries like `SELECT u FROM UserEntity u WHERE u.id=:id`

**Comment by nene** [comment]
@seguri Queries like this are already supported. Simply use the [paramTypes](https://github.com/sql-formatter-org/sql-formatter/blob/master/docs/paramTypes.md) config option.

**Comment by seguri** [comment]
@nene ah cool. Then only https://sql-formatter-org.github.io/sql-formatter/ needs to be fixed
