### ISSUE TITLE
Each run adds extra whitespace before indented multiline comments

### ISSUE THREAD

**Issue by phil-nova** [zeroturnaround/sql-formatter#101]
To repro, create an indented multiline comment, like:

SELECT
    event,
    userId
FROM
    myTable
WHERE
    /* this is a multiline
    comment */
    event = 'login'

On each call of format, lines in the multiline comment will be indented one more time. So after two runs, it would look like:

    /* this is a multiline
        comment */

After 6 runs:

    /* this is a multiline
                comment */

This doesn't happen for multiline comments that are not indented, such as those at the top of the query, or between subqueries.

The workaround seems to be to use
-- multiple
-- line
-- comments
but this is very cumbersome.

**Comment by nene** [comment]
Reproduced.

**Comment by nene** [comment]
Fixed since 3.1.0 release.
