### ISSUE TITLE
It will insert Chinese spaces into the character, If my sql string contains Chinese characters

### ISSUE THREAD

**Issue by codingwangxiansen** [zeroturnaround/sql-formatter#107]
It will insert Chinese spaces into the character, If my sql string contains Chinese characters

**Comment by nene** [comment]
Please be more specific. The following seems to work as expected:

```sql
SELECT * from mytable where field = "漢字"
```

results in:

```sql
SELECT
  *
from
  mytable
where
  field = "漢字"
```

**Comment by nene** [comment]
Aha, I see. A duplicate of #91
