### ISSUE TITLE
"FULL JOIN" formatting inserts newline after "FULL"

### ISSUE THREAD

**Issue by cofad** [zeroturnaround/sql-formatter#109]
When a select statement contains a "FULL JOIN" clause, a newline is inserted after "FULL". This doesn't happen with "INNER" and "OUTER" join clauses.

Input:
```SQL
SELECT * FROM table1 FULL JOIN table 2 ON a = b
```

Actual:
```SQL
SELECT
  *
FROM
  table1 FULL
  JOIN table 2 ON a = b
```

Expected:
```SQL
SELECT
  *
FROM
  table1
  FULL JOIN table 2 ON a = b
```
Here's a codepen demonstrating the issue:
https://codepen.io/Cofad/pen/XWjejjR

**Comment by nene** [comment]
Fixed in `4.0.0-beta.7` release.
