### ISSUE TITLE
[Question] How to get the following result ?

### ISSUE THREAD

**Issue by UserSina** [zeroturnaround/sql-formatter#111]
Is it possible to remove line breaks, comments, and extra spaces from a non formatted sql ?

**INPUT:**

![textarea](https://user-images.githubusercontent.com/44204957/105356967-68015e00-5bf4-11eb-8478-f324244e994a.PNG)

**OUTPUT:** 
> SELECT * FROM clients WHERE UPPER(first_name) LIKE('A%') AND UPPER(last_name) LIKE('F%') AND salary > 5000 AND phone = 123456;

**Comment by nene** [comment]
Nope, that's currently not supported.

As the purpose of this lib is to perform formatting, stripping formatting is currently out of scope.
