### ISSUE TITLE
Whether more configurable items can be opened in the cfg parameter？

### ISSUE THREAD

**Issue by yliu199x** [zeroturnaround/sql-formatter#113]
In our project, Freemarker will be used in the SQL file. SQL - Formatter Formatting SQL corrupts Freemarker statements. For example: "<#if stat_type = =" 0 ">" after formatting will become "< #if stat_type = =" 0 “>”(a space is added between the symbols "<" and "#"). Such a statement cannot be executed normally. Whether more configurable items can be opened in the cfg parameter.? Through the cfg parameter, improve the flexibility of the component configuration, like the following, I added a line of code that configures specialwordChars.

```js
StandardSqlFormatter.prototype.format = function format(query) {
        if (!tokenizer) {
            tokenizer = new _Tokenizer2["default"]({
                reservedWords: reservedWords,
                reservedToplevelWords: reservedToplevelWords,
                reservedNewlineWords: reservedNewlineWords,
                stringTypes: ["\"\"", "N''", "''", "``", "[]"],
                openParens: ["(", "CASE"],
                closeParens: [")", "END"],
                indexedPlaceholderTypes: ["?"],
                namedPlaceholderTypes: ["@", ":"],
                lineCommentTypes: ["#", "--"],
                specialWordChars: this.cfg.specialWordChars
            });
```

**Comment by nene** [comment]
I'm unsure. Attempting to play well with any pre-processing language is bound to be tricky.

As I understand it, in your example `<#` will be recognized as less-than operator `<` followed by comment `#`. That's sort of very core of the SQL syntax.

I guess you can hack it to work in some scenarios, but fundamentally it's pretty much impossible to solve properly. The pre-processing language knows nothing of SQL and SQL knows nothing of the pre-processing language. Even when you strip away the Freemarker tags, you will not necessarily have valid SQL. Like, one could possible write something like this:

```
SEL<#if true>ECT</#if> * FROM table;

SEL<#if false>ECT</#if> * FROM table;
```

The first line will be valid SQL SELECT, but the second line is invalid. Should they be formatted as SQL select clauses or not?

**Comment by nene** [comment]
For now, this seems pretty far-fetched feature request, so I'm closing this.
