### ISSUE TITLE
`create function` sql format error

### ISSUE THREAD

**Issue by fannheyward** [zeroturnaround/sql-formatter#116]
```sql
create function get_film_count(len_from int, len_to int)
returns int
language plpgsql
as
$$
declare
   film_count integer;
begin
   select count(*) 
   into film_count
   from film
   where length between len_from and len_to;
   
   return film_count;
end;
$$;
```

After format:

```sql
create function get_film_count(len_from int, len_to int)
returns int
language plpgsql
as
$ $ -- there is a space between dollar
declare
   film_count integer;
begin
   select count(*) 
   into film_count
   from film
   where length between len_from and len_to;
   
   return film_count;
end;
$ $; -- there is a space between dollar
```

**Comment by nene** [comment]
Stored procedures are currently completely unsupported.

So sorry, this likely won't be fixed in any near term.

**Comment by dessalines** [comment]
Would it be possible to avoid formatting those blocks? That way I can still run the sql formatter but it won't break my sql migrations.

**Comment by nene** [comment]
Well... for start, could you tell me which dialect of SQL this is?

**Comment by dessalines** [comment]
Postgres, always begins with `create (or replace) function ...`

**Comment by nene** [comment]
So, for Postgres I've just added support for dollar-quoted strings. So that should take care of the formatter touching anything inside $$...$$ block. Although it'll format the rest of this one one long line, as it knows nothing of functions.

You can try the latest beta here: https://zeroturnaround.github.io/sql-formatter/
