### ISSUE TITLE
sqlFormatter is not imported correctly following the "library way"

### ISSUE THREAD

**Issue by xavijam** [zeroturnaround/sql-formatter#118]
If you try to use `sql-formatter` installing it from npm doesn't work because the `default` export has been removed from version 3.1.0 at `sqlFormatter.js`.

**Comment by nene** [comment]
I've updated the docs.

Was this the problem, or was there something else?

**Comment by huineng** [comment]
i still think there's a problem, maybe the @types need to be updated..

TS2614: Module '"../../../../node_modules/@types/sql-formatter"' has no exported member 'format'. Did you mean to use 'import format from "../../../../node_modules/@types/sql-formatter"' instead?

![image](https://user-images.githubusercontent.com/3482445/106489153-bfd17c00-64b4-11eb-9442-f7299612f7dc.png)

**Comment by nene** [comment]
Aha... this relates to #80

**Comment by nene** [comment]
Provided the type definitions. You can now drop `@types/sql-formatter` and be able to get correct types from just `sql-formatter` alone since 4.0.1 version.

**Comment by huineng** [comment]
All good !
