### ISSUE TITLE
Code alignment

### ISSUE THREAD

**Issue by rbroth** [zeroturnaround/sql-formatter#121]
Feature request:

It would a nice feature if the formatter would do (or retain) code alignment in CREATE TABLE statements example:

```
CREATE TABLE household (
	id                  bigint                NOT NULL primary key GENERATED BY DEFAULT AS IDENTITY
	, other_text        text                  NOT NULL
	, location          geometry(Point,4326)  NULL
	, description       text                  NULL
	, an_integer_field  integer               NOT NULL
	, a_freign_key      integer               NOT NULL REFERENCES other_table(id)
);

```
Gets turned into 
```
CREATE TABLE household (
  id BIGINT NOT NULL PRIMARY key GENERATED BY DEFAULT AS IDENTITY,
  other_text text NOT NULL,
  location geometry(Point, 4326) NULL,
  description text NULL,
  an_integer_field INTEGER NOT NULL,
  a_freign_key INTEGER NOT NULL REFERENCES other_table(id)
);
```

I assume that this would be difficult to do, since no CLI formatter that I'm aware of does this ( oracle SQLDeveloper has a built-in one that does this).

**Comment by nene** [comment]
Yeah, that's likely not going to happen. It's the first time I get such a request. It's also the first time I see somebody using an SQL formatting style like that.

I've seen such alignment used with some other programming languages, but more often I've seen various style guides advising against such style, as it hurts maintainability - whenever you change the longest field name, you'll need to re-indent all the lines in a block.

Another part here is consistency. You're asking for special treatment of CREATE TABLE, but what about all the other statements. Should they also be indented using some similar system? I don't know how that would work though. And if not, then it's an awkward special treatment of CREATE TABLE.

Plus, of course, it's not trivial to implement.

Don't take it personally, but I'm closing this feature request.
