### ISSUE TITLE
white space inserted for language db2

### ISSUE THREAD

**Issue by huineng** [zeroturnaround/sql-formatter#123]
i have specified language db2 and have a select that needs to replace some hex characters

```sql
replace(AL3.NAME1, x'00', x'20') AS CUSTNAME
```

but get's replace by 

```sql
replace(AL3.NAME1, x '00', x '20') AS CUSTNAME
```

This gives an sql error

```
com.ibm.db2.jcc.am.SqlSyntaxErrorException: ILLEGAL SYMBOL "'00'". 
SOME SYMBOLS THAT MIGHT BE LEGAL ARE: AS * AT OPTION YEAR YEARS 
MONTH MONTHS DAY DAYS HOUR HOURS. SQLCODE=-104, SQLSTATE=42601, DRIVER=4.28.11
```

Let me know how this problem can be solved.. maybe can be added to a list of exceptions

[some doc on hex](https://www.ibm.com/support/knowledgecenter/SSEPEK_10.0.0/sqlref/src/tpc/db2z_charstringconstants.html)

**Comment by huineng** [comment]
I have mad a pull request after testing it out on my code https://github.com/zeroturnaround/sql-formatter/pull/127

**Comment by inferrinizzard** [comment]
Hi, this issue is fixed in my fork here:
https://github.com/inferrinizzard/prettier-sql
https://www.npmjs.com/package/prettier-sql

**Comment by nene** [comment]
Now fixed for both lowecase and uppercase `X`.
