### ISSUE TITLE
postgresql named arguments are incorrectly formatted

### ISSUE THREAD

**Issue by briandunn** [zeroturnaround/sql-formatter#125]
Named arguments generate invalid psql.

### given:

```postgresql
select make_interval(secs := 100);
select make_interval(secs => 100);
```

### actual:

```
SELECT
  make_interval(secs: = 100);
SELECT
  make_interval(secs = > 100);
```

### expected:

```
SELECT
  make_interval(secs := 100);
SELECT
  make_interval(secs => 100);
```

**Comment by inferrinizzard** [comment]
Hi, this issue is fixed in my fork here:
https://github.com/inferrinizzard/prettier-sql
https://www.npmjs.com/package/prettier-sql

**Comment by nene** [comment]
This fix is now also in master branch of sql-formatter.
