### ISSUE TITLE
Easier SQL language extension

### ISSUE THREAD

**Issue by forestfang-stripe** [zeroturnaround/sql-formatter#132]
Not sure if I missed anything obvious but it seems pretty difficult to customize any existing SQL language formatter without forking the language formatter class definition. It would be great if we could provide a consistent way to extend existing formatters.

One motivating example could be https://github.com/zeroturnaround/sql-formatter/pull/114
Another motivating example would be that if we want to support templated SQL via handlebar, we could add `{{` and `}}` to open/close parens to the dialect in question.

Lastly, it is not obvious to me what an optimal interface would look like. If you have any ideas or preferences, I'm happy to work on a PR.

**Comment by nene** [comment]
This is out of scope.

Formatting both a templating language and a language which is targeted by the template is a very hard problem. Even when doing it manually, it's hard to come up with a consistent way of doing this.
