### ISSUE TITLE
format output is not a valid SQL

### ISSUE THREAD

**Issue by capaj** [zeroturnaround/sql-formatter#135]
Tested on ` "sql-formatter": "^4.0.2",`
```
  console.log(
    format(
      `select "users".* from "users" where "users"."id" in where "certification_enrolments"."deleted_at" != 1)`
    )
  )
```

outputs 
```
select
      "users".*
    from
      "users"
    where
      "users"."id" in
    where
      "certification_enrolments"."deleted_at" ! = 1
    )
```

expected output: 
```
select
      "users".*
    from
      "users"
    where
      "users"."id" in
    where
      "certification_enrolments"."deleted_at" != 1
    )
```

the difference is there is not space between `!` and `=`

**Comment by pankgeorg** [comment]
The same happens with the `||` operator (concatenation)

**Comment by ghenkhaus** [comment]
+1 We are seeing this issue as well with `= >` when the expected output is `=>`.

**Comment by inferrinizzard** [comment]
Hi, this issue is fixed in my fork here:
https://github.com/inferrinizzard/prettier-sql
https://www.npmjs.com/package/prettier-sql

**Comment by nene** [comment]
Fixed now in master branch.
