### ISSUE TITLE
Standard SQL gives whitespaces and invalid SQL

### ISSUE THREAD

**Issue by driesvints** [zeroturnaround/sql-formatter#139]
The new standard SQL formatter in 4.x adds whitespaces for backticks. If users attempt to run this they'll run into errors for their language. Tested on v4.0.2:

```
select
  *
from
  ` database `.` table `
where
  ` database `.` table `.` column ` = 1
limit
  1
```

In previous versions this wasn't the case. We're in a situation where we don't know the SQL language so we can't it and want to fall back on standard SQL. It seems unlikely this wasn't caught before so I wanted to see what feedback you might have here.

We're currently experiencing this issue on Telescope after upgrading. I couldn't find an upgrade guide so I just updated by hand. See https://github.com/laravel/telescope/issues/1046

**Comment by driesvints** [comment]
We're using it like:

```js
import { format } from 'sql-formatter';

format(sql);
```

Where `sql` is: the SQL payload. It can be MySQL, PostgreSQL, Sqlite or MSSQL.

**Comment by driesvints** [comment]
We reverted back to v3.1.0 for the time being and will hold off on upgrading for now.

**Comment by torbjornvatn** [comment]
I see the same, will downgrade too

**Comment by namnm** [comment]
Hi guys, any update on this?

**Comment by inferrinizzard** [comment]
Hi, this issue is fixed in my fork here:
https://github.com/inferrinizzard/prettier-sql
https://www.npmjs.com/package/prettier-sql

**Comment by nene** [comment]
Fix for this is now also in master branch.

**Comment by driesvints** [comment]
Thanks @nene
