### ISSUE TITLE
"error": "Invalid regular expression: 

### ISSUE THREAD

**Issue by prakashrajPk** [zeroturnaround/sql-formatter#141]
"error": "Invalid regular expression: /^([\\p{Alphabetic}\\p{Mark}\\p{Decimal_Number}\\p{Connector_Punctuation}\\p{Join_Control}]+)/: Invalid escape"

**Comment by d4487068** [comment]
I also encountered this problem in the computer enterprise wechat.

**Comment by d4487068** [comment]
Invalid regular expression: /^([\p{Alphabetic}\p{Mark}\p{Decimal_Number}\p{Connector_Punctuation}\p{Join_Control}]+)/: Invalid escape

**Comment by nene** [comment]
Unable to reproduce.

Likely related to the platform you're running the library on. Can't really do much here without any additional information.
