### ISSUE TITLE
When there is "false" in SQL, the format will  fail

### ISSUE THREAD

**Issue by jiatianqi** [zeroturnaround/sql-formatter#147]
input 
```
CREATE TABLE run_stat(
  carId int, avg_speed double
  ) WITH (
  'connector.type' = 'jdbc',
  'connector.url' = 'jdbc:mysql://199.1XX.1XX.XXX:3306/aaa?useSSL=false',
  'connector.table' = 'mysql_run_log',
  'connector.username' = 'aaa',
  'connector.password' = 'aaa');
```
There will be errors during the formatting process, and the test will fail in this[online site](https://zeroturnaround.github.io/sql-formatter/). The current version is 4.0.2, but it is normal to use 2.3.3.

**Comment by delanym** [comment]
The tool is unusable like this

`INSERT INTO matrix (first) VALUES ('false')`

**Comment by inferrinizzard** [comment]
Hi, can you confirm if this is still an issue here: https://inferrinizzard.github.io/prettier-sql/ ?

**Comment by inferrinizzard** [comment]
Hi, this issue is fixed in my fork here:
https://github.com/inferrinizzard/prettier-sql
https://www.npmjs.com/package/prettier-sql

**Comment by baurine** [comment]
exact the same issue, reported the following error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'slice')
    at parseKey (Tokenizer.js:191:20)
    at Tokenizer2.getPlaceholderTokenWithKey (Tokenizer.js:235:21)
    at Tokenizer2.getIdentNamedPlaceholderToken (Tokenizer.js:187:19)
    at Tokenizer2.getPlaceholderToken (Tokenizer.js:182:19)
    at Tokenizer2.getNextToken (Tokenizer.js:127:147)
    at Tokenizer2.tokenize (Tokenizer.js:107:24)
    at MySqlFormatter2.format7 (Formatter.js:87:38)
    at format8 (sqlFormatter.js:74:29)
    at formatSql (index.ts:15:19)
    at index.ts:32:23
```

**Comment by baurine** [comment]
> Hi, this issue is fixed in my fork here: https://github.com/inferrinizzard/prettier-sql https://www.npmjs.com/package/prettier-sql

Big thanks @inferrinizzard , your fork resolves my issue!

**Comment by nene** [comment]
Fixed also in latest master.
