### ISSUE TITLE
Double pipes

### ISSUE THREAD

**Issue by UnleashSpirit** [zeroturnaround/sql-formatter#150]
Hi,

In postgresql (may be others) you can use double pipe to concatenate column like :
`select foo||bar as foobar from table;`

This ends up with a space between the pipes when format sql which is unvalid when copy/paste.
```sql
SELECT
  foo | | bar AS foobar
FROM
 table
```

**Comment by inferrinizzard** [comment]
Hi, this issue is fixed in my fork here:
https://github.com/inferrinizzard/prettier-sql
https://www.npmjs.com/package/prettier-sql

**Comment by nene** [comment]
Fixed also in latest master.
