### ISSUE TITLE
Incorrect formatting for scientific notation (e.g. 2.020000000000000E+003)

### ISSUE THREAD

**Issue by xstevenyung** [zeroturnaround/sql-formatter#152]
Applying format to the following query

`select 2.020000000000000E+003;`

outputs the following result

```
SELECT
  2.020000000000000E + 003;

```

but should rather output as the current format is invalid SQL

```
SELECT
  2.020000000000000E+003;

```

I'm using

`"sql-formatter": "^4.0.2"`

Related issue:
https://github.com/zeroturnaround/sql-formatter/issues/93

**Comment by inferrinizzard** [comment]
Hi, this issue is fixed in my fork here:
https://github.com/inferrinizzard/prettier-sql
https://www.npmjs.com/package/prettier-sql
