### ISSUE TITLE
PL/SQL Format document adds spaces to brackets, not valid

### ISSUE THREAD

**Issue by lissa2882** [zeroturnaround/sql-formatter#155]
When I use this extension to format a block of PL/SQL code it always adds spaces behind opening curly brackets and before closing brackets. 

`{entityid}` becomes `{ entityid }`
https://d.pr/v/DXaZHm

The code is used in NetSuite custom search formulas, and the added spaces are invalid and have to be removed. How can I adjust the settings to stop this from happening?
(PS. I'm not a developer)

**Comment by inferrinizzard** [comment]
Hi, this issue is fixed in my fork here:
https://github.com/inferrinizzard/prettier-sql
https://www.npmjs.com/package/prettier-sql

**Comment by nene** [comment]
This doesn't look like valid PL/SQL code to me. PL/SQL uses double-quotes to escape column names, not braces.

I think there's some other templating language in work in here that uses this `{ ... }` syntax, so this is really out of scope for sql-formatter.
