### ISSUE TITLE
MySQL+MariaDB: Format SET datatype in CREATE TABLE

### ISSUE THREAD

**Issue by hhhapz** [zeroturnaround/sql-formatter#159]
MySQL (and MariaDB) have a SET datatype that resembles a bit flag:
https://dev.mysql.com/doc/refman/8.0/en/set.html
https://mariadb.com/kb/en/set-data-type/

At the moment, none of the formatting languages support this, and break the formatting for the CREATE TABLE definition (presumably because it's also a keyword). 

Example (from the web demo):
![image](https://user-images.githubusercontent.com/29532600/126578178-a152966f-6c41-4c63-be0e-32cc75e5e6e1.png)

Fixing this shouldn't be terribly difficult, and  it should probably be able to get the same treatment as the ENUM datatype, at least in my mind. Is this something that would be possible/easy to fix?

**Comment by inferrinizzard** [comment]
Hi, this issue is fixed in my fork here:
https://github.com/inferrinizzard/prettier-sql
https://www.npmjs.com/package/prettier-sql
