### ISSUE TITLE
Incorrect formatting for pl/sql

### ISSUE THREAD

**Issue by nmanandhar** [zeroturnaround/sql-formatter#160]
![image](https://user-images.githubusercontent.com/9746042/126867854-fffe8e32-e436-4c0a-8109-2e39912eb712.png)

**Comment by inferrinizzard** [comment]
Hi, this issue is fixed in my fork here:
https://github.com/inferrinizzard/prettier-sql
https://www.npmjs.com/package/prettier-sql

**Comment by nene** [comment]
Fixed now also in master branch.
