### ISSUE TITLE
plsql column name with reserved word and punctuation mark

### ISSUE THREAD

**Issue by estanglerbm** [zeroturnaround/sql-formatter#166]
With plsql, column name references with a reserved word and punctuation mark (the ones that are allowed unquoted, like `#` and `$`) should not have a space between them.  Names like:

```
type#
procedure$
user#
```

This is especially prevalent in "recursive SQL" in Oracle, or queries against the low-level dictionary (that still show up everywhere).

For example:

```
select user# from t
```

currently formats like:

```
select
  user #
from
  t
```

**Comment by inferrinizzard** [comment]
Hi, this issue is fixed in my fork here:
https://github.com/inferrinizzard/prettier-sql
https://www.npmjs.com/package/prettier-sql
