### ISSUE TITLE
Add "Dense mode"

### ISSUE THREAD

**Issue by alippai** [zeroturnaround/sql-formatter#168]
This is a feature request to improve some common query patterns to make them easier to read.
The idea is to allow the maximum number of arguments, columns in one row. Currently it's always `0`.
Given:
```
SELECT symbol, trade_time last_trade, price last_price FROM trades 
LIMIT 1 OVER(PARTITION BY symbol ORDER BY trade_time DESC);
```
Now:
```
SELECT
  symbol,
  trade_time last_trade,
  price last_price
FROM
  trades
LIMIT
  1 OVER(
    PARTITION BY symbol
    ORDER BY
      trade_time DESC
  );
```
Dense with value `1` would produce:
```
SELECT
  symbol,
  trade_time last_trade,
  price last_price
FROM trades
LIMIT 1 OVER(PARTITION BY symbol ORDER BY trade_time DESC);
```
Dense with value `3` would produce:
```
SELECT symbol, trade_time last_trade, price last_price
FROM trades
LIMIT 1 OVER(PARTITION BY symbol ORDER BY trade_time DESC);
```

**Comment by inferrinizzard** [comment]
Hi, this issue is fixed in my fork here:
https://github.com/inferrinizzard/prettier-sql
https://www.npmjs.com/package/prettier-sql

**Comment by nene** [comment]
Currently in master this is now implemented with the `newline` option. For example `newline: 3`.

Though the naming of this is currently pretty bad and will likely change.
