### ISSUE TITLE
Odd PostgreSQL placeholder / bind issue (skipped value)

### ISSUE THREAD

**Issue by moltar** [zeroturnaround/sql-formatter#170]
Given the SQL:

```sql
SELECT jsonb_build_object($1::text, "id") AS result
FROM "foo"
WHERE ("authorization_token_id" = $2 AND "marketplace_id" = $3)
LIMIT $4
```

And bind values:

```
[ 'id', '00000000-0000-0000-0000-000000000000', 'ATV', 1 ]
```

The formatted result is:

```sql
SELECT
  jsonb_build_object(00000000-0000-0000-0000-000000000000 :: TEXT, "id") AS result
FROM
  "foo"
WHERE
  (
    "authorization_token_id" = ATV
    AND "marketplace_id" = 1
  )
LIMIT
  undefined
```

Notice that the first param (`id`) is gone somewhere.

**Comment by nene** [comment]
The implementation assumes that the values for named / numbered placeholders are specified with a map, like so:

```js
format("SELECT $1, $2", {
  params: {1: "foo", 2: "bar"}
});
```

But in JavaScript an array also works as an object, but of course indexes/keys start with zero.

The array is really meant for cases where the placeholders aren't named, like:

```js
format("SELECT ?, ?", {
  params: [ "foo", "bar"]
});
```

Not sure whether to change this behavior or not.
