### ISSUE TITLE
Spark reservedKeywords include some functions but not all

### ISSUE THREAD

**Issue by cccs-jc** [zeroturnaround/sql-formatter#178]
Wondering what is the intent of the reservedKeywords array.

In the spark formatter the array contains keywords and functions. Not all functions are listed (there are many missing).

Is the intent of that array to include all possible functions so that they can get capitalized or not based on the user's configuration?

**Comment by nene** [comment]
These keyword/function lists have now been reorganized. So the question shouldn't be relevant any more.
