### ISSUE TITLE
Don't add break line for  `CHARACTER SET` in MariaDbFormatter

### ISSUE THREAD

**Issue by mariadb-ThienLy** [zeroturnaround/sql-formatter#181]
Hi, seems like with current options, there is no way to archive that.
I think this is because `SET` is included in `reservedTopLevelWords`. 
Perhaps,we need an exception for `CHARACTER SET`
Current result:

    ALTER TABLE
       `test`.`t4` CHARACTER
    SET
       = dec8,
       COLLATE = dec8_swedish_ci,
       DROP COLUMN `c`,
       CHANGE COLUMN `b` `b` MEDIUMINT(11) UNSIGNED ZEROFILL NOT NULL; 

Expected result:

    ALTER TABLE `test`.`t4` 
    CHARACTER SET = dec8 , COLLATE = dec8_swedish_ci ,
    DROP COLUMN `c`,
    CHANGE COLUMN `b` `b` MEDIUMINT(11) UNSIGNED ZEROFILL NOT NULL ;

**Comment by nene** [comment]
Bug still present in latest master.

**Comment by nene** [comment]
Fixed now finally.
