### ISSUE TITLE
Formatting issue for DO $$ block

### ISSUE THREAD

**Issue by egel** [zeroturnaround/sql-formatter#183]
Hey, thanks for your attention upfront.

I recently wanted to try your formatter, which seems btw working very great and stable. 
Unfortunately, I stumble upon a problem that my SQL code has been formatted in a way that stopped working while executing while doing migrations. Hope this might help you better structure your formatter. & keep being awesome :)

Code that works fine:

```sql
DO $$
  BEGIN IF NOT EXISTS (
    SELECT
      1
    FROM
      pg_type
    WHERE
      typname = 'translations_statuses'
  ) THEN CREATE TYPE translations_statuses AS ENUM (
    'todo',
    'in_progress',
    'to_verify',
    'to_accept',
    'rejected',
    'accepted'
  );
  END IF;
END $$;
```

Code after formatting which does not work:

```sql
DO $ $ BEGIN IF NOT EXISTS (
  SELECT
    1
  FROM
    pg_type
  WHERE
    typname = 'translations_statuses'
) THEN CREATE TYPE translations_statuses AS ENUM (
  'todo',
  'in_progress',
  'to_verify',
  'to_accept',
  'rejected',
  'accepted'
);

END IF;

END $ $;
```

sql-formatter version: v4.0.0

**Comment by inferrinizzard** [comment]
Hello, what language is this?

**Comment by eatonphil** [comment]
> Hello, what language is this?

Looks like PL/pgSQL?

**Comment by nene** [comment]
This should now be fixed in latest master.

Everything between `$$ ... $$` is now treated as a string and not touched by the formatter.
