### ISSUE TITLE
uncaught syntax error. requested module doesn't provide an export named 'format'

### ISSUE THREAD

**Issue by pa1raju** [zeroturnaround/sql-formatter#188]
import  { format } from 'sql-formatter' ;

console.log(format('select * from tbl'))

after npm i tried to access the format method. But it throwing "uncaught syntax error: the requested module ../node_modules/sql-formatter/lib/sqlFormatter.js" does not provide an export named 'format'

**Comment by nene** [comment]
Unable to reproduce.
