### ISSUE TITLE
By default，backquotes wrap fields with Spaces after formatting, such as `id`  will be formatted with ` id `

### ISSUE THREAD

**Issue by roy526** [zeroturnaround/sql-formatter#192]
input:
```
select id as `id` from t_api
```

output:
```
SELECT
  id AS ` id `
FROM
  t_api
```

**Comment by xkguq007** [comment]
I got same error, any progress?

**Comment by TiboC** [comment]
I have the same issue here. 
It also adds extraneous spaces around "-" (allowed in Big Query).
`select * from `test-dev`` would be formatted 
`select 
    * 
  from 
   ` test - dev `
`

**Comment by nene** [comment]
This is now fixed in master branch.
