### ISSUE TITLE
C Style Escape Strings Improperly Formatted

### ISSUE THREAD

**Issue by jpulec** [zeroturnaround/sql-formatter#198]
It looks like when a C-style escape string is used with postgres, i.e. `E'{}'` it gets formatted to have a space between the `E` and `'{}'` which breaks the query.

**Comment by inferrinizzard** [comment]
Hi, this issue is fixed in my fork here:
https://github.com/inferrinizzard/prettier-sql
https://www.npmjs.com/package/prettier-sql

**Comment by michaelmior** [comment]
@inferrinizzard This doesn't seem to be fixed for me

```
> require('prettier-sql').format("SELECT E'\t';", {language: 'postgresql'})
"SELECT\n  E '\t';"
```

**Comment by nene** [comment]
Indeed. Not fixed by prettier-sql.

For reference. Relevant part in Postgres docs: https://www.postgresql.org/docs/9.2/sql-syntax-lexical.html#SQL-SYNTAX-STRINGS-ESCAPE

**Comment by nene** [comment]
Fixed now in master.
