### ISSUE TITLE
Change the formatting

### ISSUE THREAD

**Issue by mickeysox** [zeroturnaround/sql-formatter#20]
Hi,

Thank you for putting this together, I think it very clever.  I'm having a play with the code to try and get it to format the query how I write SQL and I was wondering if you could help.  Let's say I wanted to format the query like so.
```

SELECT COLUMN1
,      COLUMN2
FROM   TABLE1
WHERE  COLUMN1 = 'string'
GROUP  BY COLUMN1
,      COLUMN2
```

Any pointers on how I could do that?  I think its *just* a case of moving the type "word" up to the top level key words, and the commas left aligned.  I say *just*! I've been having a play but I think it's quite difficult!

Thanks.

**Comment by nene** [comment]
One way you could accomplish this is writing a tool that would take in the sql-formatter output and move the commas from end of lines to the beginning of lines. I think that would be simpler than trying to modify the indentation code inside sql-formatter itself.

**Comment by ukupat** [comment]
@mickeysox - did @nene answer your question?
