### ISSUE TITLE
postgres JSON operators are not handled

### ISSUE THREAD

**Issue by fxi** [zeroturnaround/sql-formatter#201]
Thanks for this library.

JSON operators are not working: spaces are wrongly added

```sql
SELECT '["a"]'::jsonb @> '"a"'::jsonb;
```

gives

```sql
SELECT
  '["a"]':: jsonb @ > '"a"':: jsonb;
```

Did I miss a configuration somewhere?

**Comment by inferrinizzard** [comment]
Hi, this issue is fixed in my fork here:
https://github.com/inferrinizzard/prettier-sql
https://www.npmjs.com/package/prettier-sql

**Comment by fxi** [comment]
Thanks ! 

I just tried the [online editor ](https://inferrinizzard.github.io/prettier-sql/) with 

```sql
SELECT '["a"]'::jsonb @> '"a"'::jsonb;
````
and the result was : 

```sql
SELECT
  '["a"]' :: jsonb @> '"a"' :: jsonb;
```

I will try more in depth using the package on npm. 

I don't use this package directly, but with a [vim extension](https://github.com/fannheyward/coc-sql/), so I will also contact the author to see if using your fork could be an option.

Thanks again

**Comment by nene** [comment]
This fix is now also in master branch.
