### ISSUE TITLE
Language DB2 format with $ failed

### ISSUE THREAD

**Issue by derPeterson** [zeroturnaround/sql-formatter#203]
I have specified db2 language and have a select, the values with $ characters, are separated by whitespaces, which leads to SQL error....

`SELECT * FROM TABLENAME AS C WHERE C.CLASSID IN $P{CLASSID} AND C.OID IN $P{OID} $P{INCLUDE}`

Format Result:

`SELECT * FROM TABLENAME AS C WHERE C.CLASSID IN $ P { CLASSID } AND C.OID IN $ P { OID } $ P { INCLUDE }`

I'm not a DB2 expert, but my DBeaver tool formats the $ correctly and leaves them as they were....

Thanks already for the help and for the free library, otherwise it works great.

**Comment by nene** [comment]
This should new be fixed in 6.0 release.
