### ISSUE TITLE
CLI command shows help when piped or redirected

### ISSUE THREAD

**Issue by htaketani** [zeroturnaround/sql-formatter#210]
The cli command shows help when no arguments passed.
(ref: commit 8bf6daa9dbf0d80d17edc33dc1c6701673eca7ac )

```
# show help
sql-formatter
```

However, help is also displayed when piped or redirected, as in the following example. (in version 5.1.1)

```
# pipe
echo 'select * from tbl where id = 3' | sql-formatter

# redirect
sql-formatter < input.sql
```

I send Pull Request. (PR https://github.com/zeroturnaround/sql-formatter/pull/208 )
I have modified the cli command to not show help when stdin is not tty.

**Comment by nene** [comment]
Thanks for spotting. Merged in the patch.
