### ISSUE TITLE
Release new versions on NPM

### ISSUE THREAD

**Issue by oscarlgz** [zeroturnaround/sql-formatter#212]
Latest release on NPM of this library was January 31 2021 (ver 4.0.2). Do you plan to release new versions anytime soon?

Thanks for you work!

**Comment by nene** [comment]
It's been a while, but new release is coming soon.

**Comment by nene** [comment]
There's now a 6.0.0 beta version available on npm. It should be stable with regards to not crashing, though same API details are still in flux.
