### ISSUE TITLE
[FORMATTING] if we use != in SQL queries after formatting it is adding space after ! that leads invalid Query

### ISSUE THREAD

**Issue by gitaramK** [zeroturnaround/sql-formatter#218]
`SELECT * FROM table_name WHERE col_id != '1'` 
this is simple query I am formatting 

**Expected Output**
```
SELECT
 *
FROM
 table_name
WHERE
 col_id != '1'
```

**Actual Output**
```
SELECT
 *
FROM
 table_name
WHERE
 col_id ! = '1'
```

Operator != should not formatted as ! = (space is added after ! )

**Comment by nene** [comment]
Which version of sql-formatter are you using. With the latest I get the expected output:

```
SELECT
  *
FROM
  table_name
WHERE
  col_id != '1'
```

You can try the latest 6.1.2 version in here: https://zeroturnaround.github.io/sql-formatter/
