### ISSUE TITLE
Space between two colons

### ISSUE THREAD

**Issue by sasha-alias** [zeroturnaround/sql-formatter#23]
Hi, I'm using your library for formatting SQL queries.
It works perfectly, thank you for your job.
There was discovered a minor issue with Postgresql queries though https://github.com/sasha-alias/sqltabs/issues/100
The two colons in Postgresql are used for casting a value to a certain type.
For example `SELECT '1'::int` will cast a string to an integer.
`sql-formatter` makes such queries not valid by inserting a space in between of two colons:
``` sql
SELECT
  '1': :int
```

**Comment by sean185** [comment]
Hi,

I'm using the library for formatting PostgreSQL queries and the formatter inserts spaces between PGSQL specific operators like

`meter -> '0'` becomes `meter - > '0'`
`meter ->> '0'` becomes `meter - > > '0'`
etc.

I'm kinda new to these things so do let me know how I can help, say if I could contribute by writing a language support for PGSQL, etc. 

Cheers!

**Comment by ukupat** [comment]
Issue should be fixed with https://github.com/zeroturnaround/sql-formatter/releases/tag/v1.2.1.
