### ISSUE TITLE
Throw error when trying to format unknown language

### ISSUE THREAD

**Issue by ukupat** [zeroturnaround/sql-formatter#28]
When the language parameter is anything else than "n2ql" or "db2" then we should throw an error indicating  that given language is unsupported.

**Comment by nene** [comment]
Related code in XRebel: https://bitbucket.org/zeroturnaround/xr-agent/commits/638ddbdb5e7625a7186dbe3dea349c33d9568f61

**Comment by nemecec** [comment]
@nene It is not cool to reference ZT internal repository like this on an open-source project. :-P

**Comment by nene** [comment]
Sorry @nemecec that you can't access it. But you're welcome to come to the office and I can walk you through that part of the code :)

**Comment by nemecec** [comment]
:-D

**Comment by nene** [comment]
Implemented.

**Comment by ukupat** [comment]
Thank you, sir.

**Comment by ukupat** [comment]
Don't forget to release 😌

**Comment by nene** [comment]
Just a few weeks later, and I managed to publish it :)
