### ISSUE TITLE
bad addition of spaces

### ISSUE THREAD

**Issue by PhiseySt** [zeroturnaround/sql-formatter#29]
Hellow, I'm using your library for formatting SQL queries. Language pl/sql for oracle.
It works good, thank you for your job.

Will explain please why spaces are inserted?     When I use  $ or the russian language symbols in a table name, for example:  select prod1 from base$customer or select прод1 from customer. 
It is possible to check according to link https://zeroturnaround.github.io/sql-formatter/

**Comment by ukupat** [comment]
Hey, @PhiseySt! Thanks for your report 👍 

As I can see the formatter has two issues:

1. **$ is identified as an operator** – We introduced specialWordChars configuration in https://github.com/zeroturnaround/sql-formatter/commit/c4c1da22cca69adc9f3d4579fa3325371144f009 which could help us resolve this issue.
2. **Our regex does not identify cyrillic letters as part of a word** – That was a huge surprise for me. Read more https://stackoverflow.com/a/18471465. Hint: Tokenizer class has a function createWordRegex.

I would be very grateful if you could play around with the source code, try to fix the issues and make a PR.

**Comment by PhiseySt** [comment]
Thanks for hints!
 For the solution of problems I was helped by changes in the sql-formatter.js file:

   1)   StandardSqlFormatter.prototype.format = function format(query) {
	        if (!tokenizer) {
	                ...        
	                _**lineCommentTypes: ["--"],
	                specialWordChars: ["$"]**_
	            });
	        }
	        return new _Formatter2["default"](this.cfg, tokenizer).format(query);
	    };
	    return StandardSqlFormatter;
   
2)   Tokenizer.prototype.createWordRegex = function createWordRegex() {
	        var specialChars = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : [];

	        return new RegExp("^([\\wа-яА-Я" + specialChars.join("") + "]+)");
	    };
