### ISSUE TITLE
Add support for "FETCH FIRST n ROWS ONLY"

### ISSUE THREAD

**Issue by jseminck** [zeroturnaround/sql-formatter#30]
Currently the formatter doesn't handle the FETCH keyword, so a formatted query results into:

```
SELECT
  supplier_name,
  city
FROM
  suppliers FETCH FIRST 2 ROWS ONLY
```

I expect it to format to (correct me if wrong):

```
SELECT
  supplier_name,
  city
FROM
  suppliers 
FETCH FIRST 2 ROWS ONLY
```

According to https://en.wikipedia.org/wiki/Select_(SQL)#FETCH_FIRST_clause this is standard SQL, but not supported by all dialects. However, PostgreSQL supports it which is commonly used...

I thought this was an easy fix additionally, but turns out it's a bit more tricky 😞 First I tried adding the FETCH keyword to `reservedNewlineWords` for the sqlFormatter, but it turns it into:

```
SELECT
  supplier_name,
  city
FROM
  suppliers 
  FETCH FIRST 2 ROWS ONLY // this is indented, I don't think it should be
```

Then I also tried adding the FETCH keyword to `reservedToplevelWords` for the sqlFormatter, but it turns it into:

```
SELECT
  supplier_name,
  city
FROM
  suppliers 
FETCH 
  FIRST 2 ROWS ONLY
```

**Comment by nene** [comment]
Given than FETCH is equivalent to LIMIT, the last example looks fine to me. With LIMIT you'd get:

```
SELECT
  supplier_name,
  city
FROM
  suppliers 
LIMIT 
  2
```

An alternative would be to add full "FETCH FIRST" to `reservedToplevelWords`, so you'd get:

```
SELECT
  supplier_name,
  city
FROM
  suppliers 
FETCH FIRST
 2 ROWS ONLY
```

A separate question is whether we should improve the formatter to not break stuff like `LIMIT 2` and `FETCH FIRST 2 ROWS OWNLY` to multiple lines.

*PS* After having written out this FETCH-FIRST-thing several times I'm not surprised most databases have opted for something shorter. It's surprisingly long thing to write to specify such a trivial thing.

**Comment by mathiaskissig** [comment]
`LIMIT 
  2`
and
`FETCH FIRST
 2 ROWS ONLY`
are correctly formatted according to our global formatting rules, but readability suffers.

I would prefer Joachim's example and even consider formatting LIMIT differently. E.g.
`LIMIT 2
  FETCH FIRST 2 ROWS ONLY`

**Comment by nene** [comment]
For now added a fix to at least support the following formatting:

```
FETCH FIRST
    2 ROWS ONLY;
```
