### ISSUE TITLE
Spaces are inserted before/after certain special characters

### ISSUE THREAD

**Issue by jseminck** [zeroturnaround/sql-formatter#33]
```
SELECT testäätötest FROM test
```

is formatted into:

```
SELECT
  test ä ä t ö test
FROM
  test
```

It seems the characters `ä` and `ö` cause a space to be inserted before and after the character, where ever they are being used. There are probably more characters that have the same issue, these are just two particular ones that popped up.

**Comment by nene** [comment]
@robbz23, thanks for your effort of writing a patch.

I see that your suggested regex probably comes from this StackOverflow post:

- https://stackoverflow.com/questions/23590257/match-word-characters-including-country-specific-letters-like-%C3%B6%C3%A4%C3%BC

**Comment by robbz23** [comment]
Yup thats the one.  I started on a branch for TSQL specifically we are using Sybase and we have very specific formatting requirements.  Many of us already use VS Code so I thought your library was a perfect fit.  I will submit my code when I get it working well.

**Comment by planetarydev** [comment]
Hey, I'm using a PostgreSQL database and got the same Issue when formating parameterized queries like:

`SELECT * FROM people WHERE last_name = $1`

this ends up in

```
SELECT
  *
FROM
  people
WHERE
  first_name = $ 1
```

**Comment by tuanngominh** [comment]
I have a query with [Big Query's REGEXP_CONTAINS](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#regexp_contains) 
like this
```sql
SELECT field1 FROM table1 WHERE REGEXP_CONTAINS(field1, r"value")
```
then after format it turns to
```sql
SELECT
  field1
FROM
  table1
WHERE
  REGEXP_CONTAINS(field1, r "value")
```
there is a space between `r` and `"value"` which break the query.

**Comment by godstanis** [comment]
@nene any progress on this one?

Most operators are formatted so they have separating space in the middle.

|  Raw | Formatted |
|---|---|
| `&&` | `& &` |
| `<@` | `< @` |
| `@>` | `@ >` |
| `@@` | `@ @` |
| `<->` | `< ->` |
| `'cat'::tsquery` | `'cat' :: tsquery` |

Some references:
https://www.postgresql.org/docs/10/functions-textsearch.html
https://www.postgresql.org/docs/9.6/functions-array.html

**Comment by nene** [comment]
Fixed now in 3.1.0 release

**Comment by qaisershehzad** [comment]
Query columns with special characters not working..

I have a below query and is valid query with column names with some special characters like #, $ etc

```
Select a#
 from b

```
Now when I format this query it get white space between special character and name. e.g
`Select a # from b`
which makes it invalid query. As column name is `a#`

is there a way we can allow special characters in query or format ignore while formatting so query remains valid. I am using `N1QL`

**Comment by MariuzM** [comment]
Im having the same issue where sql formater <@ to < @ causing query to break

**Comment by nene** [comment]
@MariuzM Please open another issue. Also make sure you have selected the right SQL dialect (I guess you're using PostgreSQL, and that's not the default).
