### ISSUE TITLE
INTO is optional with INSERT in some implemetations

### ISSUE THREAD

**Issue by bs-logisoft** [zeroturnaround/sql-formatter#34]
According to [stackoverflow](https://stackoverflow.com/questions/5399087/sql-server-insert-without-into) the INTO part in INSERT is optional in some implementations, e.g. SQL Server, MySQL.

When using the [demo](https://zeroturnaround.github.io/sql-formatter/) using the input:
```sql
SELECT supplier_name, city FROM suppliers
WHERE supplier_id > 500
ORDER BY supplier_name ASC, city DESC;

INSERT suppliers (supplier_name)
VALUES ('test')
```

I am getting:
```sql
SELECT
  supplier_name,
  city
FROM
  suppliers
WHERE
  supplier_id > 500
ORDER BY
  supplier_name ASC,
  city DESC;INSERT suppliers (supplier_name) -- <---- INSERT should be on next line
VALUES
  ('test')
```

Perhaps it could be simply added in [/src/languages/StandardSqlFormatter.js](https://github.com/zeroturnaround/sql-formatter/blob/master/src/languages/StandardSqlFormatter.js) within the const reservedToplevelWords.

Unfortunately I don't have the time/possibility to test this by myself, so I hope the dev team can pick this up, thanks!

**Comment by azor-orbz** [comment]
Hi, I would like to contribute on this one, can I pick this one?

**Comment by bs-logisoft** [comment]
@azor-orbz From my side you can take it 👍

**Comment by andrestaht** [comment]
@azor-orbz go ahead 😄

**Comment by azor-orbz** [comment]
Thank you,
 I am really new in this, so I tried to choice something what looks like to be easy :) Because I will surely fight with setting up env etc. I hope there is no short deadline for it.
