### ISSUE TITLE
Add support for DECLARE

### ISSUE THREAD

**Issue by SeanLMcCullough** [zeroturnaround/sql-formatter#35]
Microsoft T-SQL when containing DECLARE tags, results in a format such as:

`DECLARE @param1 VARCHAR(4) = 'asdf';DECLARE @param2 VARCHAR(4) = 'qwer';DECLARE @param3 VARCHAR(4) = 'fdsa';`

Which ends up rather messy if you have a lot of declarations.

**Comment by nene** [comment]
The sql-formatter currently doesn't support T-SQL. Like it also doesn't support PL/SQL and other procedural programming extensions for SQL.

While simply adding support for `DECLARE` would be simple, there's a whole load of additional keywords in T-SQL and the expected formatting of these constructs is somewhat different from ordinary SQL formatting.

Therefore my initial response to your request is no. Unless you want to contribute by writing full T-SQL formatting support. I also don't remember any previous requests for T-SQL support.
