### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by kensaggy** [zeroturnaround/sql-formatter#37]
Hi there,

Can you add support to make this library bower-installable?

I know the name is already taken by [this fork](https://github.com/atomlipetsk/sql-formatter), which doesn't seem to be under active development or maintenance  (this is what we used until now, but we want to move to your fork as it solves multiple issues that are still open there) but maybe you can publish it under a different name..

**Comment by nene** [comment]
I've never used bower, so I know little of what's needed for adding bower support. Would you be interested in creating a pull request?

**Comment by kensaggy** [comment]
Hi @nene - Thanks for the quick reply :) much appreciated.

There isn't much to making it available in Bower...
If you want a short-name install you basically need to register the package (find a name) and run [`bower register <my-package-name> <git-endpoint>`](https://bower.io/docs/creating-packages/#register) 

Personally I don't really mind the short-name, we can also just run `bower install https://github.com/zeroturnaround/sql-formatter.git`

What you're really missing for browser support is basically committing the "compiled" or `dist` path to the repo - so that we can include it in the markup [like this](https://bower.io/#use-packages)

Now you can just run `npm run build` locally and commit it [like this fork of sql-formatter did - see last 4 commits](https://github.com/atomlipetsk/sql-formatter/commits/master) or you can probably do a more-robust build which when merging builds and commits the `dist` automatically for you - but that's obviously more complex (either using commit hooks, or travis to do the automated).

**Comment by nene** [comment]
Hmm... I don't really like the idea of committing compiled artifacts to the repository. Is there an alternative way to achieve Bower support?

From Bower homepage I read the following message:

> ...psst! While Bower is maintained, we recommend using Yarn and Webpack for front-end projects

I take it to mean that Bower is deprecated and you're better off using something else.

Therefore unless there is a simpler way of supporting bower, I'm not really willing to do that.
