### ISSUE TITLE
Column: ENDDATE is formatted wrongly

### ISSUE THREAD

**Issue by Royvhorck1** [zeroturnaround/sql-formatter#43]
I have a problem while formatting a column called ENDDATE where the formatter will add a space between the 2 words resulting in an invalid sql query.

To recreate problem, try it out in demo at: https://zeroturnaround.github.io/sql-formatter/

Input:
`SELECT ENDDATE
from table1`

Will result in:
`SELECT
END DATE
from
  table1`

**Comment by andrestaht** [comment]
@Royvhorck1 could you provide the query that you are formatting? Also which SQL dialect are you using?

**Comment by Royvhorck1** [comment]
@andrestaht I have added an example. I am using regular SQL format

**Comment by andrestaht** [comment]
Thanks, @Royvhorck1!
Will have a look at this soon.

**Comment by Royvhorck1** [comment]
@andrestaht Thanks!

**Comment by nene** [comment]
Thanks, that was a genuine regression, introduced by the previous version.

Fixed in version 2.3.1.

Thanks for reporting!

**Comment by Royvhorck1** [comment]
No problem. thnx for the fix!
