### ISSUE TITLE
Handling comments inside SQL string

### ISSUE THREAD

**Issue by trigun539** [zeroturnaround/sql-formatter#44]
Formatting a sql string that's really long (30k) results in the following error:

`/*+ USE_HASH (F2 C3) NO_USE_NL(F2 C3) */
          ---- F3: Workload with Transpose FACT_NMs and Ratio using Total CAT (C3)`

Is there anyway I could make this work?

Thanks

**Comment by nene** [comment]
Could you provide some more details about the actual SQL that creates this error.

I tried with the following test that generates a really long SELECT statement:

```js
    it("formats long SQL", function() {
        const arr = [];
        for (let i = 0; i < 30000; i++) {
            arr.push(i);
        }

        expect(sqlFormatter.format("SELECT " + arr.join(", "))).toBe(
            "SELECT\n  " + arr.join(",\n  ")
        );
    });
```

It's definitely longer that 30k, and although it take about half a minute to run, it finishes successfully.

**Comment by trigun539** [comment]
Oh, I see now that there is like a comment inside the SQL:

`SEPT FROM (SELECT /*+ USE_HASH (F2 C3) NO_USE_NL(F2 C3) */`

Can the library handle comments? At least, it looks like a comment. If not that's ok, I'll remove it before doing the formatting.

**Comment by nene** [comment]
Indeed, your problem seems to be with comments.

The formatter doesn't recognize `/* ... */` comments. It does however recognize standard SQL comments, beginning with `--`

**Comment by trigun539** [comment]
Since the SQL string is not formatted, what I am seeing is that after the first `----` everything after that becomes a comment. Do you happen to know a way around this?

**Comment by nene** [comment]
The `--` comments are expected to end at newline.

I suppose there must have been an ending newline in this SQL of your's as well. Did you or some tool strip these newlines at some point? Try to get your hands on the original SQL which contains newlines.

Failing that, I guess you'll have to manually figure out where these comments end.

**Comment by trigun539** [comment]
@nene Thanks for your help and I have been able to remove the comments before formatting.

Here are the regex for removing comments in case anybody is interested.

```
// Remove /* */ comments
formatted = code.replace(/\/\*.+\*\//, '');

// Remove -- comments
// Additional SQL keywords could be added after SELECT in case you have comments before those keywords
formatted = formatted.replace(/(?=--).+?(?=([A-Za-z.0-9]+,|SELECT))/gi, '');
```
