### ISSUE TITLE
Support for convert reserved words to uppercase

### ISSUE THREAD

**Issue by rigogsilva** [zeroturnaround/sql-formatter#49]
Most sql formats are have reserved keywords, SELECT, FROM, WHERE, as uppercase. It would be nice to add in a configuration option to convert these words to uppercase.

**Comment by nene** [comment]
That has been requested before, but it's not quite as easy as it sounds. See #22 

If you're interested in this, then perhaps you're interested enough to move that pull request forward. The main problem there being that we currently don't have a list of keywords that could be always safely capitalized.
