### ISSUE TITLE
Make INLINE_MAX_LENGTH configurable

### ISSUE THREAD

**Issue by nene** [zeroturnaround/sql-formatter#5]
This should clearly be configurable.

But the current implementation is a bit lacking. It considers the length of the parenthesized expression in isolation, but it should also consider the current indentation, because the whole point of it is really to limit how long the lines can be. By taking the indentation into the picture, we can name the config option to something like `maxLineLength` which would be instantly understandable, v/s something like `maxParenthesizedExpressionLength`.

**Comment by ukupat** [comment]
We know that we have the same issue https://github.com/jdorn/sql-formatter/issues/59.

I was thinking about keeping  `AND ` and  `OR ` on the same line when the line is smaller than  `maxLineLength `. This could solve that issue. What do you think @nene?

**Comment by nene** [comment]
This is now configurable through the `lineWidth` option. Though for now this configuration has all the problems listed above.

**Comment by nene** [comment]
This option has been renamed to `expressionWidth`, but it's behavior is far from intuitive.

Perhaps you're interested in trying out a [new SQL formatting tool](https://github.com/nene/prettier-plugin-sql-cst) that I've written, which does support the `printWidth` option as it's implemented as a Prettier plugin and uses the same layout algorithm as Prettier.

**Comment by jonahx** [comment]
Thanks for the reply. 

> Perhaps you're interested in trying out a [new SQL formatting tool](https://github.com/nene/prettier-plugin-sql-cst) that I've written

In theory yes, but I have a couple of requirements that brought me to the cmdline tool here....

1. Need pg and tsql support
2. We have a lot of SQL that exists within template literals in JS files.  So with the command-line version, I can use a VS Code (or vim, etc) plugins to highlight lines of code inside template literals, pre-process them (eg, to replace interpolated `${vars}`), run through `sql-formatter`, post-process, then replace the original text with formatted text.   

2 is working great, except that there is no way to tell `sql-formatter` to respect the projects overall prettier `printWidth`, which would be ideal.  I am open to other solutions if you know of any.

**Comment by nene** [comment]
The only other feasible option that I know of is [SQLFluff](https://docs.sqlfluff.com/en/stable/index.html). But that one is really primarily a linter and not really that great of an option for completely reformatting SQL code. Though it does have a [max_line_length](https://docs.sqlfluff.com/en/stable/rules.html#sqlfluff.rules.Rule_L016) option and it's auto-fixable.

I'm planning to add Postrges support, but that will take time as Postgres is kinda big amongst SQL dialects. Transact-SQL is likely even more work as there are actually many dialects under this label and I find the syntax diagrams in Microsoft docs to be among the more confusing ones. However, currently Postgres support is definitely the most requested feature, so there's hope.
