### ISSUE TITLE
[BigInt value] sql-formatter in Laravel Telescope

### ISSUE THREAD

**Issue by ForzaSFerrari** [zeroturnaround/sql-formatter#53]
For me it looks like that this package has a little issue with BigInt values. 

For further informations, you can read at this Github issue https://github.com/laravel/telescope/issues/171

**Comment by nene** [comment]
For me it looks like it has not :)

While sql-formatter recognizes numbers in SQL, it treats the values as strings, never converting them to numbers. So the lost of precision is unlikely to be caused by sql-formatter.

If you still do believe it's caused by sql-formatter, please post the exact input SQL and the faulty output SQL that sql-formatter produces.

You can try out the offending SQL in here: https://zeroturnaround.github.io/sql-formatter/

**Comment by ForzaSFerrari** [comment]
I don't have these experience in that area, therefore it was a guess. But I will look.

**Comment by ForzaSFerrari** [comment]
input sql would be this
```
select
  *
from
  `images`
  inner join `users` on `images`.`userid` = `users`.`id`
  inner join `captions` on `images`.`id` = `captions`.`id`
where
  `images`.`type` = "standard_resolution"
  and `images`.`id` = 1900866953279686114
limit
  1
```

output sql would be this
```
select
  *
from
  `images`
  inner join `users` on `images`.`userid` = `users`.`id`
  inner join `captions` on `images`.`id` = `captions`.`id`
where
  `images`.`type` = "standard_resolution"
  and `images`.`id` = 1900866953279686100
limit
  1
```

**Comment by nene** [comment]
Sorry, but I'm unable to reproduce this output. Did you try it in here:

- https://zeroturnaround.github.io/sql-formatter/

Are you perhaps not using the latest sql-formatter version?

**Comment by ForzaSFerrari** [comment]
the input sql is how it would look like. the output sql is what i get as result in laravel telescope.

laravel telescope is using version 2.3.1 https://github.com/laravel/telescope/blob/6d8646b692c4202e2abc2f425fe38cf4ffe4feff/package.json#L23

**Comment by nene** [comment]
Still, I see no demonstration of a bug in sql-formatter. I can't help with issues in Lavarel Telescope.

**Comment by ForzaSFerrari** [comment]
Ok no problem. As I said, it was a guess of mine.
