### ISSUE TITLE
how to unformatter

### ISSUE THREAD

**Issue by dolphinfine** [zeroturnaround/sql-formatter#55]
when I formatter 
```
select * from xxx
```

to 

```
select
  *
from
  xxx
```
I want to send to back-end

```
select * from xxx
```

not

```
select↵  *↵from↵  xxx
```

how can I do?

**Comment by nene** [comment]
I guess you're asking for a feature to minify the SQL (strip all unnecessary whitespace).

Sorry, this library doesn't do that. No plan to implement it either. Perhaps there exists some other library to do that.

But really... there shouldn't even be a need to do that.
