### ISSUE TITLE
Remove SPACE after DELIMITER cause execution error

### ISSUE THREAD

**Issue by xiongchen2012** [zeroturnaround/sql-formatter#56]
Before format:  
```sql
DROP PROCEDURE IF EXISTS `proc_while1`;
DELIMITER ;;
CREATE PROCEDURE proc_while1(IN n int)
BEGIN
DECLARE s int;
DECLARE i int;
SET s = 0;
SET i = 0;
WHILE s <= n DO
insert into test1 value(s,i);
set s = s + 1;
set i = i + 1;
END WHILE;
END
;;
DELIMITER ;
call proc_while1(500);
```

sql-formatter will remove **SPACE** `DELIMITER ;; ` around semicolon，this cause execution exceptions.

**Comment by nene** [comment]
The root problem in here is that SQL formatter expects the delimiter to always be `;`. SQL though allows you to change the delimiter kinda dynamically mid-code. To support this we'd need a major architectural change, as this changes the grammar from context-free to context-sensitive.

sql-formatter was really built with only formatting basic SQL. Stored procedures pose a completely new formatting challenges which sql-formatter isn't built to handle.

I'd say, you're better off not using sql-formatter when dealing with stored procedures.

**Comment by nene** [comment]
Will close this as formatting of stored procedures isn't supported.
