### ISSUE TITLE
SQL-like Esper EPL syntax

### ISSUE THREAD

**Issue by robphoenix** [zeroturnaround/sql-formatter#59]
I've started looking into using this library to format [Esper EPL Queries](https://www.espertech.com/esper/). EPL mostly uses Standard SQL syntax so the library works great. EPL, though uses different comments; `//` instead of `--`. 

I'd be interested to know what you think the best way of supporting the EPL queries would be? I've not played around with the code yet, but it looks like I would need to update this line here - https://github.com/zeroturnaround/sql-formatter/blob/master/src/languages/StandardSqlFormatter.js#L101 
though I wondered if there was a way to pass in this value when calling the formatter?

I don't know yet what other differences there are between Standard SQL & EPL but would it be possible to add EPL to the languages, initially with the comment changes, and then updating for any other differences?
I'm happy to do the work and open a PR for whatever you think would be the best way to tackle this.

Thanks! :pray: :+1:

**Comment by nene** [comment]
Yeah, you've found the right spot.

But a proper way to add EPL support would be to duplicate the simply copy-paste the `StandardSqlFormatter.js` file contents to e.g. `EplFromatter.js` and modify the keyword lists and Tokenizer config so it suits EPL. Then import it in the main `sqlFormatter.js` file and register it under a name like "epl". I personally know next to nothing about EPL, so I can help you little in that regard, but I'll welcome a pull request if you're up for it.

**Comment by robphoenix** [comment]
Sounds great @nene thanks. I'll open a PR adding an EPL formatter, though it may not be 'til the week after next due to the holidays :christmas_tree:

**Comment by robphoenix** [comment]
Sorry, I've not had the opportunity I thought I would to do this.

I'm going to close this for now, and reopen it when I have something to open a PR with.

:pray:
