### ISSUE TITLE
Spark SQL?

### ISSUE THREAD

**Issue by sargun** [zeroturnaround/sql-formatter#60]
Spark SQL is pretty similar to normal SQL. Unfortunately, there are a couple keywords that don't format. Example:

```
SELECT *
FROM titus_logs LATERAL VIEW json_tuple(other_properties['fields'], 'MESSAGE', '_TRANSPORT', '_HOSTNAME') 
fields as message,
                             transport,
                             hostname 
                LATERAL VIEW json_tuple(other_properties['environment'], 'ec2Region', 'ec2AZ') 
                environment as region,
                                                   az
WHERE dateint >= 20181006
  AND dateint <= 20181010
  AND message LIKE "Linux version%"
LIMIT 10;
```

LATERAL VIEW should be on two different lines. Should I create a new SQL dialect, or somehow extend standard sql?

**Comment by nene** [comment]
Currently there's no good way of extending one dialect from another. So an easier route is to just create a new dialect.

**Comment by nene** [comment]
Spark support is now present in 3.1.0 release.
