### ISSUE TITLE
Execute sql-formatter as a command

### ISSUE THREAD

**Issue by tappoz** [zeroturnaround/sql-formatter#63]
It would be good to be able to call this tool from the command line e.g.:

Piping into it some SQL

```sh
echo "SELECT * FROM FOO_TABLE;" | sql-formatter
```

 Or providing a SQL file path as an input parameter

```sh
sql-formatter --file foo-file.sql
```

**Comment by nene** [comment]
Since 3.1.0 the command line tool is now available. See docs in README.
