### ISSUE TITLE
Format issue with mysql '@totleCount :=' syntax

### ISSUE THREAD

**Issue by wangzhengbo** [zeroturnaround/sql-formatter#69]
SELECT
                            **@totleCount** := (
                                select
                                    count(*)
                                FROM
                                    xl_exercise
                                WHERE
                                    read_article_id = #{articleId}
                            )

formatted to

 SELECT
                            **@totleCount:** = (
                                select
                                    count(*)
                                FROM
                                    xl_exercise
                                WHERE
                                    read_article_id = #{articleId}
                            )

**Comment by nene** [comment]
Closing this, as currently no MySQL support.

See the "Add MySQL support" issue: #72
