### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by mcandre** [zeroturnaround/sql-formatter#72]
Could sql-formatter support MySQL syntax?

**Comment by nene** [comment]
For reference:

- [Language structure](https://mariadb.com/kb/en/sql-language-structure/)
- [reserved words](https://mariadb.com/kb/en/reserved-words/)
- [SQL statements](https://mariadb.com/kb/en/sql-statements/)
- [operators](https://mariadb.com/kb/en/operators/)

**Comment by nene** [comment]
I've added MariaDB support, which should also cover most of MySQL. Available in `4.0.0-beta.4`

**Comment by nene** [comment]
And MySQL support is now also present in `4.0.0-beta.5`
