### ISSUE TITLE
Formatting "line-comment" with "\r\n" are not support 

### ISSUE THREAD

**Issue by namepain** [zeroturnaround/sql-formatter#78]
Some system end line with `\r\n`, and the LINE_COMMENT_REGEX is `/^((?:#|--).*?(?:\n|$))/`.
So the situation like `-- some line comment xxx \r\n balabala` cant not be formatted right.

Hope to support this situation. Many thanks!

**Comment by kufii** [comment]
I saw this was fixed in PR #64. In the meantime while we wait for it to be merged you can use my fork I published with this fix. https://www.npmjs.com/package/sql-formatter-plus

**Comment by nene** [comment]
This fix is now available in 3.1.0 release.
