### ISSUE TITLE
Newlines between SQL statements

### ISSUE THREAD

**Issue by InstanceOfMichael** [zeroturnaround/sql-formatter#88]
I would like (at least the option: `{ newLinesBetweenStatements: default 1 }`) for extra newlines between statements.
```sql
SELECT
    *
FROM
    x;
SELECT
    *
FROM
    y;
```
could instead become (with `{ newLinesBetweenStatements: 3 }`):
```sql
SELECT
    *
FROM
    x;


SELECT
    *
FROM
    y;
```

**Comment by nene** [comment]
This feature is now implemented in 3.1.0 release.
