### ISSUE TITLE
[Bug]Chinese alias formatting insert spaces

### ISSUE THREAD

**Issue by netnr** [zeroturnaround/sql-formatter#91]
![image](https://user-images.githubusercontent.com/10579621/71453928-ef4d8980-27c8-11ea-8fd4-9d15b02741a7.png)

`select * from table1 表名`

**Comment by justwang62** [comment]
how to solve?

**Comment by netnr** [comment]
结合使用，https://sqlformat.darold.net

demo：https://ss.netnr.com/sqlformatter

**Comment by justwang62** [comment]
你好，我引入之后运行报错，format js报错

**Comment by nene** [comment]
Related PR: #86

**Comment by nene** [comment]
Fixed now in 3.1.0 release.
