### ISSUE TITLE
Scientific notation support

### ISSUE THREAD

**Issue by HarryNing** [zeroturnaround/sql-formatter#93]
The scientific notation A * 1e-4 in sql formatted to  A * 1e -4,  there is a space after e. 
Jsql parser throws this exception:
>net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "-" "-"  at line 8, column 58.

Source Sql:
```
SELECT A * 1e-4 FROM TABLE1 WHERE 1 = 1
```
Formatted Sql: 
```
SELECT
  A * 1e -4
FROM
  TABLE1
WHERE
  1 = 1
```

**Comment by nene** [comment]
Fixed now in 3.1.0 release.
