### ISSUE TITLE
[Bug] Regex strings get formatted to invalid SQL due to inserted space

### ISSUE THREAD

**Issue by Ekrekr** [zeroturnaround/sql-formatter#94]
The valid SQL input of

```sql
select
  regexp_extract (r'abc')
```

gets converted to the invalid SQL input of

```sql
select
  regexp_extract (r 'abc')
```

This SQL is invalid because of the space inserted after the `r` and before the `'`.

**Comment by Ekrekr** [comment]
My bad, valid in BigQuery but not standard SQL!

**Comment by nene** [comment]
@james-lukensow-cbm are you really sure about this? I works just fine on the [demo page](https://sql-formatter-org.github.io/sql-formatter/).

- What exactly do you mean by latest build?
- Which exact parameters did you use when invoking the formatter?

**Comment by james-lukensow-cbm** [comment]
Here is a valid regex: `regexp_extract (r'abc')`

The output becomes `regexp_extract (r 'abc')`, which will fail when executing via BigQuery.

**Comment by james-lukensow-cbm** [comment]
@nene You're right, when I select BigQuery, it formats correctly. False alarm.
